### PR TITLE
Beam to. Fixes #141

### LINKED ISSUE #141: Teleport to someone in 3d

### PR DESCRIPTION
**Pull request by Sgeo**
Click a user in the list to beam to them.

Does not currently respect SharedZone.beamToViewpoint, and SharedZone.beamToDistance support was written but is untested.

May not have ideal results when beaming to someone who is in 2D.

### CODE REVIEW

**Comment by Sgeo** [comment]
Tested beamToDistance in Cyberhood, works great.
The functionality doesn't seem to work well in Gameshow, and I'm not sure why not.

**Comment by Sgeo** [comment]
This should probably be a smooth transition instead of an instant teleport.

Inserting a viewpoint and moving to it would probably accomplish this, and is what some documentation claims Blaxxun Contact does.

**Comment by dburleson** [comment]
> This should probably be a smooth transition instead of an instant teleport.
> 
> Inserting a viewpoint and moving to it would probably accomplish this, and is what some documentation claims Blaxxun Contact does.

Is this still a Work in Progress then?

**Comment by dburleson** [comment]
@Sgeo Can you confirm if this complete or a work in progress? You're last comment makes me believe it's a Work In Progress.

**Comment by Sgeo** [comment]
Haven't looked at it in a while, I think it could be merged as-is or I could try the insert-a-viewpoint approach. Also I just realized I can actually check what Blaxxun Contact does in terms of smoothness vs instant.

**Comment by dburleson** [comment]
> Haven't looked at it in a while, I think it could be merged as-is or I could try the insert-a-viewpoint approach. Also I just realized I can actually check what Blaxxun Contact does in terms of smoothness vs instant.

@Sgeo It sounds like the you might want to look at improving this a bit more then if you perhaps have better ways to do it.

**Review by dburleson — APPROVED** [review]
Works a charm.

**Pull request merged**
