### PR TITLE
fix #100: show username casing stored in database

### LINKED ISSUE #100: Login is not case sensitive
A user with the username `User1` is able to log in as `uSeR1`, and the system will accept it. Their name will be displayed as such throughout their session. Usernames should be case sensitive.

### PR DESCRIPTION
**Pull request by RomainStorai**
Related to issue #100 

This should show on UI the stored casing username. (see [Comment](https://github.com/CybertownRevival/ctr/issues/100#issuecomment-1148274731) from @dburleson)

To be tested.

### CODE REVIEW

**Comment by dburleson** [comment]
@RomainStorai Thanks for the submission. Is there any chance you could resolve the conflict from the latest update? We have recently made a huge change to the api code by introducing a db query builder.

**Comment by RomainStorai** [comment]
> @RomainStorai Thanks for the submission. Is there any chance you could resolve the conflict from the latest update? We have recently made a huge change to the api code by introducing a db query builder.

Should be good now!

**Comment by RomainStorai** [comment]
*Little explaination of what I did*:

When creating the session, a token is created and needs the username as input.
Instead of putting the username given by the user
```diff
- ..., username, ....
```
I basically put the username from the fetched data
```diff
+ ..., user.username, ....
```

**Review by smile0711 — APPROVED** [review]
This fix does change the token to the actual username according to the db.  It also limits impostors by keeping case sensitivity on signup.  Example, no one can sign up as "Smile07" as the code still sees it as "smile07".   However, if I sign in as "SmilE07", this fix will put the token to the actual username "smile07".

**Comment by TheMikeSanto** [comment]
This PR includes a merge commit, which can make reading commit history annoying once there are enough of them. In the future, please update your feature branches via `git rebase` to avoid this.

cc @RomainStorai @smile0711

**Pull request merged**
