### PR TITLE
Fixes case insensetivity of username on login

### LINKED ISSUE #100: Login is not case sensitive
A user with the username `User1` is able to log in as `uSeR1`, and the system will accept it. Their name will be displayed as such throughout their session. Usernames should be case sensitive.

### PR DESCRIPTION
**Pull request by liamcloss**
Fixes #100 where login is not case sensitive.

### CODE REVIEW

**Comment by dburleson** [comment]
@liamcloss can you confirm if your fix satisfies the requirements stated in my comment?
https://github.com/CybertownRevival/ctr/issues/100#issuecomment-1148274731

**Comment by liamcloss** [comment]
@dburleson it does indeed. Any attempt to login using a username capitalisation  which doesn't align with the capitilisation of the username within the database will fail to authenticate the user.

**Comment by dburleson** [comment]
@liamcloss I think normal usability allows incorrect case authentication for usernames. However, the UI should use the stored casing from the database.

Example:

User enters: uSer1
DB successfully authenticates: User1
UI uses: User1

@TheMikeSanto Can you confirm if you agree with the above as at the moment, this fix will require exact casing to authenticate.

**Comment by liamcloss** [comment]
Doesn't meet use case requires and superseded by #106

**Pull request closed without merging**
